name: Flutter-SDK AppImage
on:
  workflow_dispatch:
jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          path: AppDir
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|qt-hello-world|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppDir/AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage